### ISSUE TITLE
Cómo instalar ó cómo ejecutar

### ISSUE THREAD

**Issue by paulinohuerta** [gallardoalcala/AgendaCitas#1]
Hola,

¿Es posible tener alguna recomendación de como desplegar la aplicación y probar?
¿Es necesario preparar algo en la Base de Datos?

Muchas gracias.

Paulino

**Comment by gallardoalcala** [comment]
**Para ejecutar la aplicación:**

git clone https://github.com/gallardoalcala/AgendaCitas.git
cd AgendaCitas
./mvnw spring-boot:run

El acceso se realiza mediante: http://localhost:8080/

Para configurar la BD:

ejecutar el fichero database.sql
