### ISSUE TITLE
Issue al ejecutar

### ISSUE THREAD

**Issue by paulinohuerta** [gallardoalcala/AgendaCitas#2]
Hola,

1. He visto que el script database.sql se localiza en la carpeta raíz del proyecto (no en src/main/resources/sql).

2. No es posible ejecutar la aplicación tal como se indica,

_./mvnw spring-boot:run_

He conseguido ejecución mediante

 **mvn clean install spring-boot:run**
luego de resolver el issue explicado más abajo.

He debido de indicar cuál clase de las canditates...(esto es otro issue, ¿OK?)

Unable to find a single main class from the following candidates [com.acme.DemocrudApplication, com.example.AgendaCitasApplication]

En pom.xml en el 'properties element' he debido agregar
<start-class>com.acme.DemocrudApplication</start-class>

Gracias.

Paulino

**Comment by gallardoalcala** [comment]
Entendido. Me dispongo a corregir los errores mencionados.
Muchas Gracias, y disculpas.

Samuel.
